### ISSUE TITLE
Rich Salz version?

### ISSUE THREAD

**Issue by nickd4** [DavidKinder/AberMUD2#4]
Hi David,

I was wondering if you could provide a binary or a link to the Rich Salz archive? I found two different versions of the abermud.zip which unpack the same, so I believe I have that, although an authoritative source (as a link or binary) for the abermud.zip would not hurt at all. 

I ask because I am interested in trying to reconstruct the original B source code. I assume the B source has been lost, as had the original Thompson B compiler, but enough fragments of compiled library code survived that the B compiler has been reconstructed accurately.

So it would be cool to have some more substantial applications written in B (at the moment we only have a collection of command line utilities from Unix V1/V2 as far as I am aware). A glance through your source shows that it is mostly B compatible, I did not check carefully but if struct is used it can be replaced with array, etc.

Cheers, Nick

**Comment by DavidKinder** [comment]
Sorry, but I didn't keep a copy of the Rich Salz archive, and doing a quick Google search I can't see anything that reminds me of where it originally came from.
